apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-service
spec:
  replicas: {{ .Values.authService.replicaCount }}
  selector:
    matchLabels:
      {{- include "ecommerce.selectorLabels" (dict "component" "auth-service") | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "ecommerce.selectorLabels" (dict "component" "auth-service") | nindent 8 }}
        {{- include "ecommerce.labels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- include "ecommerce.podSecurityContext.node" . | nindent 8 }}
      containers:
        - name: auth-service
          image: {{ include "ecommerce.image" (dict "registry" .Values.global.imageRegistry "repo" .Values.authService.image.repository "tag" .Values.authService.image.tag) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.authService.service.port }}
              name: http
          securityContext:
            {{- include "ecommerce.containerSecurityContext" . | nindent 12 }}
            readOnlyRootFilesystem: true
          env:
            - name: PORT
              value: {{ .Values.authService.service.port | quote }}
          envFrom:
            - configMapRef:
                name: shopnova-config
            - secretRef:
                name: shopnova-secrets
          resources:
            {{- toYaml .Values.authService.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.authService.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.authService.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-service
spec:
  type: {{ .Values.authService.service.type }}
  selector:
    {{- include "ecommerce.selectorLabels" (dict "component" "auth-service") | nindent 4 }}
  ports:
    - port: {{ .Values.authService.service.port }}
      targetPort: {{ .Values.authService.service.port }}
      protocol: TCP
      name: http
