apiVersion: v1
kind: Secret
metadata:
  name: shopnova-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  EMAIL_USER: {{ .Values.secrets.emailUser | quote }}
  EMAIL_PASS: {{ .Values.secrets.emailPass | quote }}
